// flow-typed signature: 29b8b5260ddf8d204f1af6204fc7a104
// flow-typed version: <<STUB>>/find_v^0.2.7/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'find'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'find' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'find/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'find/index' {
  declare module.exports: $Exports<'find'>;
}
declare module 'find/index.js' {
  declare module.exports: $Exports<'find'>;
}
declare module 'find/test/test.js' {
  declare module.exports: $Exports<'find/test/test'>;
}
